
# Gem::Specification for Backcall-0.0.2
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{backcall}
  s.version = "0.0.2"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Lerner"]
  s.date = %q{2008-06-12}
  s.description = %q{Add basic memory-efficient before and after callbacks, easily}
  s.email = %q{ari.lerner@citrusbyte.com}
  s.extra_rdoc_files = ["CHANGELOG", "lib/backcall.rb", "lib/core/proc.rb", "README"]
  s.files = ["CHANGELOG", "lib/backcall.rb", "lib/core/proc.rb", "Manifest", "Rakefile", "README", "spec/callback_spec.rb", "spec/spec_helper.rb", "backcall.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://blog.citrusbyte.com}
  s.post_install_message = %q{For more information, check http://blog.citrusbyte.com
*** Ari Lerner @ <ari.lerner@citrusbyte.com> ***}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Backcall", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{backcall}
  s.rubygems_version = %q{1.1.1}
  s.summary = %q{Add basic memory-efficient before and after callbacks, easily}

  s.add_dependency(%q<facets>, [">= 0"])
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rubygems'
# require 'echoe'
# 
# task :default => :test
# 
# Echoe.new("backcall") do |p|
#   p.author = "Ari Lerner"
#   p.email = "ari.lerner@citrusbyte.com"
#   p.summary = "Add basic memory-efficient before and after callbacks, easily"
#   p.url = "http://blog.citrusbyte.com"
#   p.dependencies = %w(facets)  
#   p.install_message = "For more information, check http://blog.citrusbyte.com\n*** Ari Lerner @ <ari.lerner@citrusbyte.com> ***"
#   p.include_rakefile = true
# end